### ISSUE TITLE
Robotick - Unify Robotick Configuration with MJCF, YAML, and Deployment Layers

### ISSUE THREAD

**Issue by paulwconnor-ai** [robotick-labs/robotick#68]
# 🧠 Ticket: Unify Robotick Configuration with MJCF, YAML, and Deployment Layers

**Date:** 2025-05-22  
**Owner:** Paul Connor
**System:** Robotick Engine / Magg-E  
**Category:** Architecture / Config / Tooling

---

## ✅ Summary

This ticket formalizes the evolving approach to unified configuration in the Robotick project — using a combination of:

- **MJCF** for physical structure, dynamics, and simulation
- **Custom YAML (`robotick.yaml`)** for semantic control config, ROS2 node layout, and deployment
- **Auto-generated ROS2 launch files and headers**
- Integration with our **existing YAML workload system** (defining computational pipelines, modules, and data flows)

The goal: **one robot description to rule them all**, serving simulation, planning, control, and deployment across hardware and simulation.

---

### 1. `magg-e.xml` (MJCF)
- Physical model: links, joints, sensors, dynamics
- Used directly in MuJoCo and planning systems
- May include a `<custom>` or `<compiler>` tag with reference to `magg-e.yaml`

### 2. `magg-e.yaml` (Robotick config)
- High-level description of:
  - ROS2 nodes (name, package, launch, remappings)
  - Controllers and workloads
  - Deployment targets (SSH to Pi2, Pi5, etc.)
  - Optional motion planning or gesture systems
- Can act as a manifest for code generation

### 3. Existing Robotick Engine YAMLs
- Define workloads (modules, dependencies, data routes)
- Must be referenced or embedded within `magg-e.yaml` to allow:
  - Consistent ROS-to-Engine integration
  - Modular reuse across robots
  - Auto-wiring of perception → control → actuation

---

## 🔁 Deployment Design

`magg-e.yaml` will optionally define:

```yaml
deployment:
  targets:
    pi2:
      host: 192.168.1.42
      user: robotick
      role: low_level
      deploy:
        - src: firmware/balance_loop.bin
          dst: /home/robotick/bin/
          run: systemctl restart balance-loop

    pi5:
      host: 192.168.1.43
      user: robotick
      role: perception
      deploy:
        - src: launch/magg-e.launch.py
          dst: ~/ros2_ws/
          run: ros2 launch magg-e.launch.py
```

This enables:

- Auto SSH deployment
- Fast multi-device orchestration
- Clean separation between real-time control (e.g. Pi2) and rich perception (e.g. Pi5)

---

## 🔄 Integration Goals

- [ ] Design and document the `robotick.yaml` schema
- [ ] Add support for referencing or embedding existing workload YAMLs
- [ ] Create a CLI tool `robotick deploy` to perform multi-host deploys
- [ ] Extend `robotick describe` to include MJCF + control + workload metadata
- [ ] Establish launch config templates for ROS2

---

## 📁 Related Tickets

- 🎛️ Engine Config Loader Refactor
- 🚀 Dave Runtime Planning via MuJoCo
- 🧪 Magg-E Workload Test Suite
- 🤖 Define Magg-E Initial MJCF Model

---

**End of Ticket**
